import {
  Activity,
  AppWindow,
  Archive,
  Bell,
  Blocks,
  Box,
  Bug,
  Calendar,
  ChartBar,
  ChartLine,
  ChartPie,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Database,
  Download,
  Eye,
  File,
  FileText,
  Flag,
  Folder,
  Gauge,
  Globe,
  HardDrive,
  Heart,
  Image,
  Key,
  LayoutGrid,
  List,
  Lock,
  Mail,
  MessageSquare,
  Package,
  Plug,
  Puzzle,
  RefreshCw,
  Rocket,
  Search,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Table,
  Terminal,
  Upload,
  User,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Íconos que un plugin puede usar por nombre (kebab-case de lucide). */
export const PLUGIN_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "app-window": AppWindow,
  archive: Archive,
  bell: Bell,
  blocks: Blocks,
  box: Box,
  bug: Bug,
  calendar: Calendar,
  "chart-bar": ChartBar,
  "bar-chart-3": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  clock: Clock,
  cloud: Cloud,
  "cloud-upload": CloudUpload,
  code: Code,
  database: Database,
  download: Download,
  eye: Eye,
  file: File,
  "file-text": FileText,
  flag: Flag,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  "hard-drive": HardDrive,
  heart: Heart,
  image: Image,
  key: Key,
  "layout-grid": LayoutGrid,
  list: List,
  lock: Lock,
  mail: Mail,
  "message-square": MessageSquare,
  package: Package,
  plug: Plug,
  puzzle: Puzzle,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  terminal: Terminal,
  upload: Upload,
  user: User,
  users: Users,
  wrench: Wrench,
  zap: Zap,
};

export const FALLBACK_PLUGIN_ICON = "puzzle";

/** Nombre de ícono conocido o `puzzle` si falta o no existe. */
export function resolvePluginIconName(name: string | null | undefined): string {
  return name && Object.prototype.hasOwnProperty.call(PLUGIN_ICONS, name) ? name : FALLBACK_PLUGIN_ICON;
}

export function pluginIcon(name: string | null | undefined): LucideIcon {
  return PLUGIN_ICONS[resolvePluginIconName(name)] ?? Puzzle;
}
